// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDggBaoaQz5P5IJ3XCzN-aYaE9bZ8EYGJg',
    appId: '1:244302597623:web:2f0f167eb22d8b24a432f2',
    messagingSenderId: '244302597623',
    projectId: 'wasey-6462d',
    authDomain: 'wasey-6462d.firebaseapp.com',
    storageBucket: 'wasey-6462d.firebasestorage.app',
    measurementId: 'G-DWJZ8NGTYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MYFwj3Mbd8bqAMXxcOWSbUy6e6Rt9fM',
    appId: '1:244302597623:android:3288879e88ee13cba432f2',
    messagingSenderId: '244302597623',
    projectId: 'wasey-6462d',
    storageBucket: 'wasey-6462d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67nIIB3uzl_Ix4shL4A6pVZHrGgN06-k',
    appId: '1:244302597623:ios:d223d50f5a580345a432f2',
    messagingSenderId: '244302597623',
    projectId: 'wasey-6462d',
    storageBucket: 'wasey-6462d.firebasestorage.app',
    iosClientId: '244302597623-66g4h5p3fa0nlb01tv4jlnh5k3erfban.apps.googleusercontent.com',
    iosBundleId: 'com.waseyapp.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDggBaoaQz5P5IJ3XCzN-aYaE9bZ8EYGJg',
    appId: '1:244302597623:web:5f601a1e106cbce9a432f2',
    messagingSenderId: '244302597623',
    projectId: 'wasey-6462d',
    authDomain: 'wasey-6462d.firebaseapp.com',
    storageBucket: 'wasey-6462d.firebasestorage.app',
    measurementId: 'G-QEFJQTWSE2',
  );

}